### ISSUE TITLE
Could not generate a decorated class for type NuGetPush

### ISSUE THREAD

**Issue by afischer-opentext-com** [Itiviti/gradle-nuget-plugin#78]
I recently tried to update the build system of an older project, bumping the java version, gradle and gradle plugin versions to something current. What I now observe is the following. 

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\project\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.ullink.nuget', version: '2.18']
> Failed to apply plugin [id 'com.ullink.nuget']
   > Could not create task ':gaia_msi:nugetPush'.
      > Could not create task of type 'NuGetPush'.
         > Could not generate a decorated class for type NuGetPush.
            > java.lang.ClassFormatError: Duplicate method name "setTimeout" with signature "(Ljava.lang.Object;)V" in class file com/ullink/NuGetPush_Decorated
```

The used gradle version is 6.1.1 and the used Java version is OpenJDK 13.0.0 x64 on Windows. 
The gradle files itself do not call the setTimeout method and do not use the NuGetPush feature. 

In the past the stuff worked with Java 11 and 12 and Gradle 5.3 with nuget plugin in version 2.15. 

Can someone recommend any workaround for this or has an idea where this comes from?

Edit: The last working combination of plugin and gradle is 2.18 with gradle 6.0.1. Everything else, including 6.2-RC-1 does not work.

**Comment by ngyukman** [comment]
Hi, it is because gradle just added timeout in base class in gradle 6, can be fixed by removing it in #79
and use timeout from gradle directly if necessary

**Comment by citizenmatt** [comment]
Is there a timescale to merge this PR and publish a 2.19 release? I'd love to move up to Gradle 6, but this is a blocker, unfortunately.

**Comment by ngyukman** [comment]
Sorry just released, but I didn't have time to test it thoroughly with the new Input Output requirements in gradle 6 / 7
if you encounter any problem, please notify us, thanks

**Comment by citizenmatt** [comment]
That’s great, thank you!
